# fly.toml app configuration file generated for linkleaner on 2023-05-26T12:03:42+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "linkleaner"
primary_region = "ams"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
image = "registry.fly.io/linkleaner:latest"

[mounts]
  source = "linkleaner_data_1"
  destination = "/data"
